#url: https://blog-cgarces.c9users.io/
url: http://127.0.0.1:4000/

proofer:
  check_html: true
  url_ignore:
    - http://www.linkedin.com/in/carlos-garces-0aa21831
  typhoeus:
    timeout: 10
    headers:
      User-Agent: "Mozilla/5.0 (compatible; robot de Google/2.1; +http://www.google.com/bot.html)"
