environment: development
url: https://blog-cgarces.c9users.io/

proofer:
  url_ignore:
    - http://www.linkedin.com/in/carlos-garces-0aa21831
  check_html: true


#  url_ignore:
#    - "#comments"
#    - !ruby/regexp '/https?:\/\/(www)?\.youtube\.com\/watch\?v=.*/i'
#    - !ruby/regexp '/https?:\/\/(www)?\.youtube\.com\/watch\?v=.*/i'
#github:
#  repository_nwo: "benbalter/benbalter.github.com"
#  owner_url: "https://github.com/benbalter"
#  repository_url: "https://github.com/benbalter/benbalter.github.com"