environment: development
url: https://blog-cgarces.c9users.io

proofer:
  check_html: true
  url_ignore:
    - "#comments"
    - /edit/master/404.html  
    - http://www.linkedin.com/in/carlos-garces-0aa21831
    - !ruby/regexp '/http:\/\/github\.com\/CGarces\/CGarces\.github\.io\/edit\/master\/_posts\/.*/i'
  typhoeus:
    timeout: 20
    headers:
      User-Agent: "Mozilla/5.0 (compatible; robot de Google/2.1; +http://www.google.com/bot.html)"
