# Permalinks
#
permalink: pretty
highlighter: rouge
markdown: redcarpet
redcarpet:
  extensions: ["strikethrough"]

gems:
  - jekyll-sitemap
  - jekyll-paginate
#permalink: /:year/:month/:day/:title/
# Setup
title:               Carlos Garcés' Blog
tagline:             'Software Engineering. Bienvenido a mi blog.'

description:         'Blog realizado con <a href="http://jekyllrb.com" target="_blank">Jekyll</a> para escribir los problemas que resuelvo en mi tiempo libre.'
url:                 http://cgarces.github.io
baseurl:             ''
paginate:            5
excerpt_separator:   <!-- leer mas -->

# About/contact
author:
  name:              Carlos Garcés
  url:               http://cgarces.github.io
  email:             carlos.garces@gmail.com
  linkedin:          http://www.linkedin.com/in/carlos-garces-0aa21831
  
# Custom vars
version:             1.0.0

#SEO options
seo:
  title: false
  post_schema: BlogPosting	
exclude: 
  - README.md
  - Gemfile
  - Gemfile.lock
  - .c9

# prose config
prose:
  rooturl: '_posts'
  siteurl: 'http://cgarces.github.io'
  #relativeLinks: 'http://cgarces.github.io/links.jsonp'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "categories"
        field:
          element: "multiselect"
          label: "Add Categories"
          placeholder: "Add Categories"
          alterable: true
      - name: "title"
        field:
          element: "text"
          label: "Post title"
          placeholder: "Title"
          alterable: true
